name: yangon_taxi
description: "Yangon Taxi - 仰光打车应用"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ^3.27.4

dependencies:
  flutter:
    sdk: flutter

  # 基础UI
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10

  # 登录/注册
  intl_phone_field: ^3.0.1
  pin_code_fields: ^8.0.1
  sms_autofill: ^2.4.1

  # 状态 & 存储
  provider: ^6.1.1
  shared_preferences: ^2.3.2

  # 地图和定位
  google_maps_flutter: ^2.10.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  flutter_polyline_points: ^2.1.0

  # 网络
  http: ^1.2.1

  # 头像上传
  image_picker: ^1.1.2

  # 多语言
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.1

  # SOS / 拨号
  url_launcher: ^6.3.1

  # KBZ Pay QR
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
